language: swift
osx_image: xcode10.2
before_install: 
- gem install xcpretty
- gem install cocoapods
script: 
- xcodebuild -scheme GenericGeometry_iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' test | xcpretty --test --color
- pod lib lint --allow-warnings
