name: GenericGeometry
options:
  bundleIdPrefix: com.shopgun
  deploymentTarget:
    iOS: 8.0
    macOS: 10.9
    tvOS: 9.0
    watchOS: 2.0
targets:
  GenericGeometry:
    platform: [iOS, tvOS, watchOS, macOS]
    type: framework
    scheme:
      gatherCoverageData: true
      testTargets: ['GenericGeometryTests_${platform}']
    settings:
      SWIFT_VERSION: 5.0
    sources: 
      - path: Sources

  GenericGeometryTests:
    platform: [iOS, tvOS, watchOS, macOS]
    type: bundle.unit-test
    dependencies: [{target: 'GenericGeometry_${platform}'}]
    settings:
      SWIFT_VERSION: 5.0
    sources:
      - path: Tests
